export { default as apiClient } from "./apiClient";
export * as authApi from "./authApi";
export * as customerUserApi from "./customerUserApi";
export * as customerDashboardApi from "./customerDashboardApi";
export * as customerHistoryApi from "./customerHistoryApi";
export * as customerProfileApi from "./customerProfileApi";
export * as adminUserApi from "./adminUserApi";
export * as adminDashboardApi from "./adminDashboardApi";
export * as adminServiceApi from "./adminServiceApi";
export * as customerBookingApi from "./customerBookingApi";
export * as adminBookingApi from "./adminBookingApi";
export * as customerVoucherApi from "./customerVoucherApi";
export * as customerConfigApi from "./customerConfigApi";
export * as vehicleModelApi from "./vehicleModelApi";
export * as adminPromotionApi from "./adminPromotionApi";
export * as customerLoyaltyApi from "./customerLoyaltyApi";
export * as adminAnalyticsApi from "./adminAnalyticsApi";
export * as staffDashboardApi from "./staffDashboardApi";
export * as staffQueueApi from "./staffQueueApi";
export * as staffCustomerApi from "./staffCustomerApi";
export * as customerCarApi from "./customerCarApi";

