export { default as apiClient } from "./apiClient";
export * as authApi from "./authApi";
export * as userApi from "./userApi";
export * as carApi from "./carApi";
export * as serviceApi from "./serviceApi";
export * as bookingApi from "./bookingApi";
export * as paymentApi from "./paymentApi";
export * as promotionApi from "./promotionApi";
export * as loyaltyApi from "./loyaltyApi";
export * as analyticsApi from "./analyticsApi";
export * as staffApi from "./staffApi";
